version: '3'

services:
  website:
    build: ./frontend/
    ports:
      - "127.0.0.1:3080:80"
    restart: always
  backend:
    build: ./backend/
    environment:
      - DB_HOST: ''
      - DB_USER: ''
      - DB_PASS: ''
      - DB_NAME: ''
      - SESS_SECRET: ''
      - SALT: ''
      - HCAP_ENABLE: ''
      - HCAP_SECRET: ''
    ports:
      - "127.0.0.1:3000:3000"
    restart: always